### ISSUE TITLE
运行 Louvain算法/louvain.py时报错

### ISSUE THREAD

**Issue by Gezelligh3id** [lwten/Community-detection#1]
报错内容：
Traceback (most recent call last):
  File "louvain.py", line 79, in <module>
    partition = community.best_partition(A)
  File "D:\Anaconda3\lib\site-packages\python_louvain-0.4-py3.7.egg\community\community_louvain.py", line 203, in best_partition
  File "D:\Anaconda3\lib\site-packages\python_louvain-0.4-py3.7.egg\community\community_louvain.py", line 266, in generate_dendrogram
TypeError: Bad graph type, use only non directed graph

**Comment by gaohai2017** [comment]
我也遇到同样的报错

**Comment by zhuzhu-lu** [comment]
感觉louvain这个代码和最后运行出来的结果不太对的上，这里报错是因为有向图没有转换成无向图
